name: Build Test Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name : shell
        run: echo "git checkout done"
  test:
    needs: build
    runs-on : ubuntu-latest
    steps:
     - name: test the code 
       run: echo "test"
  deploy:
    runs-on : ubuntu-latest
    needs: test
    steps:
     - name: test the code 
       run: echo "test"
        
        
  
      
