name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: "project-e647ce93-877c-4c89-b70"
  REGION: "us-central1"
  SERVICE: "my-service"
  GAR_REPOSITORY: "my-repository"
  IMAGE_NAME: "my-image"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/258473375695/locations/global/workloadIdentityPools/github-demo/providers/github"
          service_account: "github-wif@project-e647ce93-877c-4c89-b70.iam.gserviceaccount.com"

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            ${REGION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${{ github.sha }}
